#include "llc_enum.h"

#ifndef LLC_MICRO_H
#define LLC_MICRO_H

namespace llc
{
    GDEFINE_ENUM_TYPE (ESP_ERROR, int32_t);
    GDEFINE_ENUM_VALUE(ESP_ERROR, OK                            , OS_OK                );
    GDEFINE_ENUM_VALUE(ESP_ERROR, NO_MEM                        , ESP_NO_MEM           );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_ARG                   , ESP_INVALID_ARG      );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_STATE                 , ESP_INVALID_STATE    );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_SIZE                  , ESP_INVALID_SIZE     );
    GDEFINE_ENUM_VALUE(ESP_ERROR, NOT_FOUND                     , ESP_NOT_FOUND        );
    GDEFINE_ENUM_VALUE(ESP_ERROR, NOT_SUPPORTED                 , ESP_NOT_SUPPORTED    );
    GDEFINE_ENUM_VALUE(ESP_ERROR, TIMEOUT                       , ESP_TIMEOUT          );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_RESPONSE              , ESP_INVALID_RESPONSE );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_CRC                   , ESP_INVALID_CRC      );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_VERSION               , ESP_INVALID_VERSION  );
    GDEFINE_ENUM_VALUE(ESP_ERROR, INVALID_MAC                   , ESP_INVALID_MAC      );
    GDEFINE_ENUM_VALUE(ESP_ERROR, NOT_FINISHED                  , ESP_NOT_FINISHED     );
    GDEFINE_ENUM_VALUE(ESP_ERROR, WIFI_BASE                     , ESP_WIFI_BASE        );
    GDEFINE_ENUM_VALUE(ESP_ERROR, MESH_BASE                     , ESP_MESH_BASE        );
    GDEFINE_ENUM_VALUE(ESP_ERROR, FLASH_BASE                    , ESP_FLASH_BASE       );
    GDEFINE_ENUM_VALUE(ESP_ERROR, HW_CRYPTO_BASE                , ESP_HW_CRYPTO_BASE   );
    GDEFINE_ENUM_VALUE(ESP_ERROR, MEMPROT_BASE                  , ESP_MEMPROT_BASE     );
    GDEFINE_ENUM_VALUE(ESP_ERROR, FLASH_OP_TIMEOUT              , ESP_FLASH_OP_TIMEOUT );
    GDEFINE_ENUM_VALUE(ESP_ERROR, FLASH_OP_FAIL                 , ESP_FLASH_OP_FAIL    );
    GDEFINE_ENUM_VALUE(ESP_ERROR, FAIL                          , OS_ERROR             );

    GDEFINE_ENUM_TYPE (ESP_TCP, int32_t);
    GDEFINE_ENUM_VALUE(ESP_TCP, OK                    ,  0);
    GDEFINE_ENUM_VALUE(ESP_TCP, MEM                   , -1);
    GDEFINE_ENUM_VALUE(ESP_TCP, BUF                   , -2);
    GDEFINE_ENUM_VALUE(ESP_TCP, TIMEOUT               , -3);
    GDEFINE_ENUM_VALUE(ESP_TCP, ROUTING               , -4);
    GDEFINE_ENUM_VALUE(ESP_TCP, IN_PROGRESS           , -5);
    GDEFINE_ENUM_VALUE(ESP_TCP, ILLEGAL_VALUE         , -6);
    GDEFINE_ENUM_VALUE(ESP_TCP, WOULDBLOCK            , -7);
    GDEFINE_ENUM_VALUE(ESP_TCP, ADDRESS_IN_USE        , -8);
    GDEFINE_ENUM_VALUE(ESP_TCP, IS_CONNECTING         , -9);
    GDEFINE_ENUM_VALUE(ESP_TCP, ALREADY_CONNECTED     , -10);
    GDEFINE_ENUM_VALUE(ESP_TCP, NOT_CONNECTED         , -11);
    GDEFINE_ENUM_VALUE(ESP_TCP, LOW_LEVEL_NETIF_ERROR , -12);
    GDEFINE_ENUM_VALUE(ESP_TCP, CONNECTION_ABORTED    , -13);
    GDEFINE_ENUM_VALUE(ESP_TCP, CONNECTION_RESET      , -14);
    GDEFINE_ENUM_VALUE(ESP_TCP, CLOSED                , -15);
    GDEFINE_ENUM_VALUE(ESP_TCP, ILLEGAL_ARGUMENT      , -16);
} // namespace

#endif // LLC_MICRO_H
